git add tools/ansible/README.md
git add tools/ansible/nginx/Makefile
git add tools/ansible/nginx/README.md
git add tools/ansible/nginx/nginx.yml
git add tools/binutils.md
git add tools/couchdb.md
git add tools/db/cap_theorem.md
git add tools/db/mongodb.md
git add tools/docker/Dockerfile.in
git add tools/docker/Dockerfile.out
git add tools/docker/docker.md
git add tools/git.md
git add tools/kubernetes/k8s-on-virtualbox/README.md
git add tools/kubernetes/nfs/README.md
git add tools/kubernetes/nfs/default-storage.yaml
git add tools/kubernetes/nfs/local-volumes.yaml
git add tools/kubernetes/nfs/local-volumes2.yaml
git add tools/kubernetes/nfs/nfs-server.yaml
git add tools/kubernetes/nfs/wordpress-deployment.yaml
git add tools/ranking_interns/intern.py
git add tools/virtualbox.md
git add tools/vsftp/README-anon.md
git add tools/vsftp/vsftpd-anon.conf
