FROM alpine:3.7

ENV ANSIBLE_VERSION=2.5.0
ENV ANSIBLE_LIBRARY=/ansible/library
ENV PATH=/ansible/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV PYTHONPATH=/ansible/lib
ENV ANSIBLE_SSH_PIPELINING=True
ENV ANSIBLE_ROLES_PATH=/ansible/playbooks/roles
ENV ANSIBLE_RETRY_FILES_ENABLED=false
ENV ANSIBLE_HOST_KEY_CHECKING=false
ENV ANSIBLE_GATHERING=smart

ENV BUILD_PACKAGES="bash curl tar openssh-client sshpass git python py-boto py-dateutil py-httplib2 py-jinja2 py-paramiko py-pip py-yaml ca-certificates"

RUN set -x && \
    \
    echo "==> Adding build-dependencies..." && \
    apk --update add --virtual build-dependencies gcc musl-dev libffi-dev openssl-dev python-dev && \
    \
    echo "==> Upgrading apk and system..." && \
    apk update && apk upgrade && \ 
    \
    echo "==> Adding Python runtime..." && \
    apk add --no-cache ${BUILD_PACKAGES} && \
    pip install --upgrade pip && \
    pip install python-keyczar docker-py && \
    \
    echo "==> Installing Ansible..." && \
    pip install ansible==${ANSIBLE_VERSION} && \
    \
    echo "==> Cleaning up..." && \
    apk del build-dependencies && \
    rm -rf /var/cache/apk/* && \
    \
    echo "==> Adding hosts for convenience..." && \
    mkdir -p /etc/ansible /ansible && \
    \
    echo "[local]" >> /etc/ansible/hosts && \
    \
    echo "localhost" >> /etc/ansible/hosts


# CMD ["/bin/sh"]
# ADD file:6ee19b92d5cb1bf143947fe2e2481cb3b353d42e1e54888a8ba48c03dd4155f2 in /
