all:
	echo "speficy target"

setup: clean touch
	echo "setup"

clean:
	rm -f *.avi
	rm -f *.smi
	rm -f *.lst

touch:
	touch video1.avi video2.avi video3.avi
	touch subtitle1.smi subtitle2.smi subtitle3.smi
